### ISSUE TITLE
Proposal: Merge of puppet extensions

### ISSUE THREAD

**Issue by blindly** [jgreat/vscode-puppetlinter#1]
Hi. I'm the maintainer of the other puppet extension for vscode. Mine provides language syntax, snippets, but no linting. How about we join forces and have 1 awesome extension that does syntax, templates, snippets, and linting?

https://marketplace.visualstudio.com/items?itemName=Borke.Puppet

**Comment by pjmagee** [comment]
@jgreat Any update or views on adding puppet linter to the other Puppet VSCode Extension?

**Comment by jgreat** [comment]
Sorry must have missed this message.  I responded on your issue.
